name: Refresh database with updated media data

on:
  schedule:
    # At 6 AM every day
    - cron: '0 6 * * *'
jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: trigger-update
        run: |
            curl --location --request POST 'https://mediascout.herokuapp.com/update-db' \
            --header 'Content-Type: application/json' \
            --data-raw '{"auth_code": "${{secrets.UPDATE_TOKEN}}"}'