name: Refresh database with updated media data

on:
  schedule:
    # At 6 AM every day
    - cron: '0 6 * * *'
jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: trigger-update
        run: curl \
        -X POST \
        -H "Content-Type: "application/json" \
        https://mediascout.herokuapp.com/update-db \
        -d ${{secrets.UPDATE_TOKEN}}